[build]
  command = "curl -fsSL https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-linux-x64-release.zip -o dart-sdk.zip && unzip -q dart-sdk.zip && export PATH=\"$PATH:$PWD/dart-sdk/bin:$HOME/.pub-cache/bin\" && dart pub global activate jaspr_cli && jaspr build"
  publish = "build/jaspr/"
